### PR TITLE
Firefox 204 response

### PR DESCRIPTION
**Pull request by naugtur**
Improved on #112

### CODE REVIEW

**Comment by TehShrike** [comment]
That test fails in at least Chrome, Firefox, and Safari - the server is returning a 404 for that response instead of a 204.  It passes in Phantom but nowhere else I've tested so far.

**Comment by reqshark** [comment]
the thing that would make it a mock firefox response is some UserAgent string in the request like 

`Mozilla/5.0 (Windows; U; Win98; en-US; rv:0.9.2) Gecko/20010725 Netscape6/6.1`

I was thinking about that userAgent string, and I'm wondering whether this happens only on Windows or also on other operating systems.

**Comment by naugtur** [comment]
@TehShrike try npm install first. I changed run-browser and it's not upstream yet.

@reqshark - I don't get what you mean :)

**Comment by TehShrike** [comment]
@naugtur I did (and the updated timeout test passed in all browsers).

@reqshark the test is meant to assert something about Firefox's XHR client, not how the server responds to Firefox requests.

**Comment by naugtur** [comment]
Ok, tests are failing because I specified the mock server only for `npm test` command :)
Pushed an update

**Comment by TehShrike** [comment]
lgtm

**Pull request merged**
