### PR TITLE
Tweaks to convenience methods

### LINKED ISSUE #96: Convenience APIs
Hey! Love this module — it's awesome. I'm wondering if you're open to one or both of the following convenience APIs in the same vein as `request`:

* `xhr.post`, `xhr.put`, etc. as shortcuts for their respective methods.

* Providing a string as the first parameter as the url for the request, with options as they are provided as the second parameter.

This would enable requests like this:

```js
xhr.post("http://example.com", function (err, resp) {
  // ...
})
``` 

These would allow for more expressive xhr calls, though they'd introduce more than one way to do things and could slightly complicate this simple library with a magical API. IMHO this would be worth the tradeoff, but I thought I'd reach out before creating a PR or a wrapper library.

Thanks again.

### PR DESCRIPTION
**Pull request by naugtur**
Removed unnecessary dependency, fixed IE8 support, minor fixes in params handling
Fixes #96

### CODE REVIEW

**Comment by wbinnssmith** [comment]
Looking good! Thanks for digging into the size of `for-each`. I've merged this back into my PR and reorganized the README in the direction you set out.

**Comment by naugtur** [comment]
Haha, I edited the readme too, but got into cross-browser tests before pushing. I'll pull yours in.

It'll take a while for me to make func-tests pass again in real browsers because of CORS issues. But I'm on it.

**Comment by naugtur** [comment]
@Raynos I'm merging it this weekend. Let me know if you feel like stopping me ;)

**Comment by wbinnssmith** [comment]
:+1: sounds good to me. I'll close out #97.

**Pull request merged**
